#!/bin/bash
# Ansible managed: /workspace/users/albandri10/env/ansible-nabla/roles/alban.andrieu.shell/templates/build.sh.j2 modified on 2016-09-02 16:50:22 by albandri on albandri-laptop-misys
# This file was generated by ansible for localhost

DOCKERNAME="nabla/ansible-shell"

time docker build -t $DOCKERNAME .

echo
echo "This image is a trusted docker.io Image."
echo
echo "To pull it"
echo "    docker pull $DOCKERNAME"
echo
echo "To use this docker:"
echo "    docker run -d -P $DOCKERNAME"
echo
echo "To run in interactive mode for debug:"
echo "    docker run -t -i $DOCKERNAME bash"
echo
