---

#
# Test Playbook
#

- hosts: localhost
  sudo: true
  roles:
    - role: ../

  vars_files:
  - [ "roles/shell/defaults/main.yml" ]  
  - [ "roles/shell/vars/default.yml" ]
  - [ "roles/shell/vars/version.yml" ]  
  - [ "roles/shell/vars/custom-{{ ansible_distribution }}-{{ ansible_architecture }}.yml", "roles/shell/vars/custom-{{ ansible_distribution }}.yml" ]  
  
  vars:
    docker_files_generated_directory: ""
    docker_files_enable: no
    jenkins_home: "/var/lib/jenkins"
    jenkins_slave_home: "{{ jenkins_home }}"
    jenkins_jdk7_enable: no

#- include: docker/integration-tests.yml
