---
# This playbook contains common plays that will be run on all nodes.

- name: Install bash shell (Debian only)
  apt: pkg={{ item }} state=present
  when: ansible_distribution == 'Debian' 
  with_items:
    - bash
#    - csh
#    - ksh

- name: Create env directory
#  file: path={{ shell_env_directory }} state=directory
  file: path={{ shell_env_directory }} state=directory mode=0700 owner={{ shell_env_owner }}
    
- name: Configure dev.env.sh file
  template: src=dev.env.sh.j2 dest={{shell_env_directory}}/dev.env.sh
  tags: configure

#cygwin
- name: Configure .bashrc file
  template: src=.bashrc-cygwin.j2 dest={{home}}/.bashrc-cygwin.j2
  when: shell_cygwin_enabled  
  tags: configure
  tags: cygwin

- name: Configure .bashrc file
  template: src=.bashrc.j2 dest={{home}}/.bashrc.j2
  when: !shell_cygwin_enabled 
  tags: configure
