---
# This playbook contains common plays that will be run on all nodes.

- name: Install csh shell (Debian only)
  apt: pkg={{ item }} state=present
  when: ansible_distribution == 'Debian'    
  with_items:
    - csh
#    - todo

- name: Create env directory
#  file: path={{ shell_env_directory }} state=directory
  file: path={{ shell_env_directory }} state=directory mode=0700 owner={{ shell_env_owner }}
  
- name: Configure dev.env.csh file
  template: src=dev.env.csh.j2 dest={{shell_env_directory}}/dev.env.csh
  tags: configure

#Cygwin
- name: Configure .cshrc file
  template: src=.cshrc-cygwin.j2 dest={{home}}/.cshrc
  when: shell_cygwin_enabled  
  tags: configure
  tags: cygwin

- name: Configure .bashrc file
  template: src=.cshrc.j2 dest={{home}}/.cshrc.j2
  when: !shell_cygwin_enabled 
  tags: configure
