---
# This playbook contains common plays that will be run on all nodes.

- name: shell | Install ksh shell (Debian only)
  apt: pkg={{ item }} state=present
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  with_items:
    - ksh
