---
# This playbook contains common plays that will be run on all nodes.

- name: Include OS-specific default variables.
  #include_vars: "{{ ansible_os_family }}.yml"
  include_vars: "default.yml"
  
- name: Include OS-specific version variables.  
  include_vars: "version.yml"
  
- name: Include OS-specific custom variables.  
  include_vars: "custom-{{ ansible_distribution }}.yml"
  #include_vars: "{{ ansible_distribution }}.yml"
  
- include: shell.yml
  when: shell_enabled
  tags: [shell]

- include: bash.yml
  when: shell_bash_enabled
  tags: [bash]

- include: csh.yml
  when: shell_csh_enabled
  tags: [csh]

- include: ksh.yml
  when: shell_ksh_enabled
  tags: [ksh]

- name: Copy Dockerfile
  template: src=Dockerfile.j2 dest={{ docker_files_generated_directory }}/Dockerfile mode=0777
  when: docker_files_enable

- name: Copy build.sh
  template: src=build.sh.j2 dest={{ docker_files_generated_directory }}/build.sh mode=0777
  when: docker_files_enable
