---
# This playbook contains common plays that will be run on all nodes.

- debug: msg="SHELL is {{ ansible_env.SHELL }} "

- name: shell | Check user
  user: name={{ shell_owner }} state=present

- name: shell | Check user home directory
  stat: path={{ shell_owner_home }}
  register: home_present

- debug: msg=" shell | Path exists and is a directory"
  when: home_present.stat.isdir is defined and home_present.stat.isdir == true

- name: shell | Configure log4j.lcf file
  template: src=log4j.lcf.j2 dest={{home}}/log4j.lcf
  ignore_errors: true
  when: shell_log4j_enabled
  tags: log4j

- name: shell | Configure log4j.properties file
  template: src=log4j.properties.j2 dest={{home}}/log4j.properties
  ignore_errors: true  
  when: shell_log4j_enabled
  tags: log4j

- name: shell | Configure log4j.xml file
  template: src=log4j.xml.j2 dest={{ home }}/log4j.xml
  ignore_errors: true
  when: shell_log4j_enabled
  tags: log4j

# rlogin
- name: shell | Uninstall xinetd for rlogin rsh rexec
  apt: >
    pkg={{ item }}
    state=absent
    purge=yes
    force=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' and shell_rlogin_enabled == false
  tags: package
  with_items:
    - xinetd

- name: shell | Install xinetd for rlogin rsh rexec (Debian only)
  apt: pkg={{ item }} state=present
  when: ansible_distribution == 'Debian' and shell_rlogin_enabled
  with_items:
    - xinetd
  tags: rlogin

- name: shell | Configure rhosts (rlogin) file
  template: src=.rhosts.j2 dest={{home}}/.rhosts
  when: shell_rlogin_enabled
  tags: rlogin

- name: shell | Configure hosts.equiv (rlogin) file
  template: src=hosts.equiv.j2 dest=/etc/hosts.equiv
  when: shell_rlogin_enabled
  tags: rlogin
