---
##################################
####### ENV GLOBAL PARAMETERS
##################################

{{DEV_VERSION}}:10

{{DEV_MODE}}:1
{{DEFAULT_ENV_LOADED}}:10

########

{{DRIVE_PATH}}:
{{PROJECT_HOME}}:${DRIVE_PATH}/workspace/users
#{{PROJECT_USER}}:{{UNIX_USERNAME}}{{DEV_VERSION}}
{{PROJECT_USER}}:{{UNIX_USERNAME}}
{{USER_PATH}}:${PROJECT_HOME}/{{PROJECT_USER}}{{DEV_VERSION}}
{{WORKSPACE_ENV}}:${PROJECT_HOME}/${PROJECT_USER}${PROJECT_VERSION}/env

{{PROJECT_VERSION}}:{{DEV_VERSION}}
{{PROJECT_MAJOR_VERSION}}:{{PROJECT_VERSION}}
{{PROJECT_MINOR_VERSION}}:02
{{PROJECT_PATCH_VERSION}}:01
{{PROJECT_EXTRACTION}}:cpp
{{PROJECT_PATH}}:{{USER_PATH}}/{{PROJECT_EXTRACTION}}
{{PROJECT_BUILD_TYPE}}:target
{{PROJECT_TARGET_PATH}}:${DRIVE_PATH}/${PROJECT_BUILD_TYPE}
{{PROJECT_DEPLOY_PATH}}:${PROJECT_TARGET_PATH}/deploy
{{PROJECT_PKG_PATH}}:${PROJECT_TARGET_PATH}/pkg
{{PROJECT_BIN_PATH}}:${PROJECT_TARGET_PATH}/bin/${ARCH}
{{PROJECT_WEB_PATH}}:${PROJECT_TARGET_PATH}/{{APP_SERVER_MODE}}

{{PROJECT_THIRDPARTY_PATH}}:${DRIVE_PATH}/thirdparty

{{WORKSTATION}}:localhost
#{{WORKSTATION_REMOTE}}:localhost:0.0
{{WORKSTATION_REMOTE}}::0.0
#{{NABLA_HOST}}:localhost
{{NABLA_HOST}}:home.nabla.mobi

#################################

{{ECLIPSE_DEBUG_PORT}}:29{{USER_INDEX_ID}}
{{DEBUG_OPTIONS}}:-Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address={{ECLIPSE_DEBUG_PORT}},server=y,suspend=n

#################################

{{PROMPT}}:'$P$G'
{{EDITOR}}:vi
{{TERM}}:xterm
{{COWSAY}}:

{{PROJECT_DATABASE_PATH}}:${PROJECT_THIRDPARTY_PATH}/database

#{{DEFAULT_LOG_PATH}}:{{PROJECT_TARGET_PATH}}/work/log

# weblogic | jboss | tomcat
{{APP_SERVER_MODE}}:jboss

# tomcat
{{APP_SERVER_ADMIN_PORT}}:8005
{{APP_SERVER_PORT}}:8280
{{APP_SERVER_HTTP_SPORT}}:8443
{{APP_SERVER_AJP_PORT}}:8009

{{LOG4J_ACTIVE_APPENDER}}:CONSOLE, SOCKETSERV, FILE
{{LOG4J_ROOT_CATEGORY}}:DEBUG, {{LOG4J_ACTIVE_APPENDER}}
{{LOG4J_SERVER_NAME}}:PROJECT
{{LOG4J_SERVER_FILE}}:/tmp/project.log
{{LOG4J_SERVER_PORT}}:4445
{{LOG4J_SERVER_HOST}}:localhost
#{{LOG4J_SERVER_PATTERN}}:{{LOG4J_SERVER_NAME}} - #%d{ABSOLUTE} %5p %c{1}:%L - %m%n
{{LOG4J_SERVER_PATTERN}}:{{LOG4J_SERVER_NAME}} - %d{yyyy/MM/dd HH:mm:ss}  %-5p [%t] %c{2} - %m%n

#{{MAVEN_LOCAL_REPO_PATH}}:~/.m2/repository
#{{MAVEN_LOCAL_REPO_PATH}}:{{DRIVE_PATH}}/repo
{{MAVEN_LOCAL_REPO_PATH}}:${env.WORKSPACE}/.m2/repository
#{{M2_SETTINGS}}:${WORKSPACE_ENV}/home/.m2/settings.xml
{{M2_SETTINGS}}:${PROJECT_DEV}/.m2/settings.xml

{{JAVA_HOME}}:${DRIVE_PATH/usr/lib/jvm/jdk{{JAVA_MAJOR_VERSION}}
{{PYTHON_DIR}}:${DRIVE_PATH/usr/lib/python
{{PYTHON_EXE}}:${DRIVE_PATH/usr/bin/python
#setenv SCONS_DIR ${PYTHON_DIR}
#setenv SCONS_DIR ${PYTHON_DIR}/Lib/site-packages/scons-{{SCONS_MAJOR_VERSION}}
{{SCONS_DIR}}:${DRIVE_PATH/usr/lib/scons
{{SCONS_PATH}}:${SCONS_DIR}/script
#{{SCONS_PATH}}:${SCONS_DIR}/SCons/Script
{{SCONS_EXE}}:${DRIVE_PATH/usr/bin/scons
{{SCONS_ALIAS}}:{{SCONS_EXE}}
#{{SCONS_ALIAS}}:${SCONS_DIR}/scons.py
#{{SCONS_ALIAS}}:${SCONS_DIR}/scons/scons.py
{{CMAKE_HOME}}:${DRIVE_PATH}/usr/share/cmake-{{CMAKE_MAJOR_VERSION}}
{{M2_HOME}}:${DRIVE_PATH}/usr/share/maven3
{{ANT_HOME}}:${DRIVE_PATH}/usr/share/ant
{{DIFF_CMD}}:svndiff
{{QT_DIR}}:${DRIVE_PATH}/usr/lib/qt3
{{TOMCAT_HOME}}:${DRIVE_PATH}/var/lib/tomcat7
{{CATALINA_HOME}}:${DRIVE_PATH}/usr/share/tomcat7
{{CATALINA_BASE}}:{{TOMCAT_HOME}}
{{ECLIPSE_HOME}}:${DRIVE_PATH}/workspace/eclipse
{{HUDSON_HOME}}:${DRIVE_PATH}/workspace/hudson
{{JENKINS_HOME}}:${DRIVE_PATH}/jenkins
{{SONAR_HOME}}:${DRIVE_PATH}/workspace/sonar
{{SONAR_RUNNER_HOME}}:${DRIVE_PATH}/workspace/sonar-runner
{{CHROME_BIN}}:${DRIVE_PATH}/usr/bin/google-chrome
{{TIBCO_HOME}}:${DRIVE_PATH}/TODO
{{CONKY_HOME}}:${DRIVE_PATH}/TODO

{{CROWD_INSTALL}}:${DRIVE_PATH}/workspace/crowd
{{CROWD_HOME}}:${DRIVE_PATH}/var/crowd-home
{{FISHEYE_HOME}}:${DRIVE_PATH}/workspace/fecru
{{FISHEYE_INST}}:${DRIVE_PATH}/workspace/fisheye
{{NEXUS_HOME}}:${DRIVE_PATH}/workspace/nexus
{{JBOSS_HOME}}:jboss-{{JBOSS_VERSION}}
{{MD_HOME}}:${DRIVE_PATH}/MagicDraw-UML-16.5
{{OPENGROK_TOMCAT_BASE}}:{{TOMCAT_HOME}}
