#!/bin/bash

echo ""
echo "	Welcome to"
echo "                     _     _"
echo "                    | |   | |"
echo "         _ __   __ _| |__ | | __ _ "
echo "        | '_ \ / _' | '_ \| |/ _' |"
echo "        | | | | (_| | |_) | | (_| |"
echo "        |_| |_|\__,_|_.__/|_|\__,_|"
echo ""
echo "	Nabla Docker integration machine"
echo "	================================"
echo -n "	Daily docker update status ... "
echo -n "	Currently running containers ... "
docker ps -q | wc -l
docker ps -a --format '\t{{.Names}}\t\t{{.Status}}'
echo ""

screenfetch
#neofetch
