#!/bin/bash

echo ""
echo "	Welcome to"
echo "                     _     _"
echo "                    | |   | |"
echo "         _ __   __ _| |__ | | __ _ "
echo "        | '_ \ / _' | '_ \| |/ _' |"
echo "        | | | | (_| | |_) | | (_| |"
echo "        |_| |_|\__,_|_.__/|_|\__,_|"
echo ""
echo "	Nabla Docker integration machine"
echo "	================================"
echo -n "	Daily docker update status ... "
#if [ $(tail -1 /home/$USER/update-docker-images.logs) = "SUCCESS" ]
#then
#	echo -e "\033[1;32mOK\033[0m"
#else
#	echo -e "\033[0;31mKO\033[0m"
#fi
echo -n "	Currently running containers ... "
docker ps -q | wc -l
docker ps -a --format '\t{{.Names}}\t\t{{.Status}}'
echo ""

screenfetch
#neofetch
